import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "KisanSahayak",
    tagline: "Empowering Farmers with AI-Powered Agricultural Guidance",
    getStarted: "Get Started",
    learnMore: "Learn More",
    dashboard: "Dashboard",
    weather: "Weather",
    crops: "Crops",
    chatbot: "AI Assistant",
    soilAnalysis: "Soil Analysis",
    resources: "Resources",
    pestDisease: "Pest & Disease",
    advisories: "Advisories",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome",
    loading: "Loading...",
    error: "Error",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    next: "Next",
    previous: "Previous",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    viewAll: "View All",
    heroTitle: "Smart Farming Starts Here",
    heroSubtitle: "Get personalized crop guidance, weather alerts, and expert farming advice powered by AI",
    featuresTitle: "Comprehensive Agricultural Support",
    weatherTitle: "Real-Time Weather & Forecasts",
    weatherDesc: "5-day forecasts with farming recommendations",
    cropGuidanceTitle: "Crop Selection Guidance",
    cropGuidanceDesc: "Choose the right crops for your soil and season",
    aiChatTitle: "AI-Powered Assistant",
    aiChatDesc: "24/7 support for all your farming queries",
    resourceTitle: "Resource Optimization",
    resourceDesc: "Track and optimize water, fertilizer, pesticide usage",
    soilTitle: "Soil Analysis",
    soilDesc: "Get fertilizer and nutrient recommendations",
    pestTitle: "Pest & Disease Management",
    pestDesc: "Early warnings and treatment solutions",
    todayWeather: "Today's Weather",
    temperature: "Temperature",
    humidity: "Humidity",
    rainfall: "Rainfall",
    wind: "Wind Speed",
    recommendedCrops: "Recommended Crops",
    season: "Season",
    soilType: "Soil Type",
    waterReq: "Water Requirement",
    expectedYield: "Expected Yield",
    profit: "Profit Estimate",
    duration: "Duration",
    days: "days",
    resourceUsage: "Resource Usage",
    water: "Water",
    fertilizer: "Fertilizer",
    pesticide: "Pesticide",
    optimal: "Optimal",
    current: "Current",
    efficiency: "Efficiency",
    recentAdvisories: "Recent Advisories",
    critical: "Critical",
    warning: "Warning",
    info: "Info",
    askQuestion: "Ask me anything about farming...",
    voiceInput: "Voice Input",
    sendMessage: "Send",
    analyzing: "Analyzing...",
    soilAnalysisTitle: "Soil Nutrient Analysis",
    nitrogenLevel: "Nitrogen (N)",
    phosphorusLevel: "Phosphorus (P)",
    potassiumLevel: "Potassium (K)",
    phLevel: "pH Level",
    organicMatter: "Organic Matter",
    getRecommendations: "Get Recommendations",
    recommendations: "Recommendations",
    pestDiseaseTitle: "Pest & Disease Identification",
    symptoms: "Symptoms",
    treatment: "Treatment",
    prevention: "Prevention",
    severity: "Severity",
    high: "High",
    medium: "Medium",
    low: "Low",
    farmLocation: "Farm Location",
    farmSize: "Farm Size",
    phoneNumber: "Phone Number",
    language: "Language",
    english: "English",
    hindi: "हिंदी",
    servingFarmers: "Serving 50,000+ farmers across India",
    trusted: "Trusted by farmers nationwide",
    exploreCrops: "Explore crop recommendations for your region and season",
    latestAdvisories: "Latest farming recommendations and alerts",
    noCropsAvailable: "No Crops Available",
    cropsWillAppear: "Crop recommendations will appear here",
    noAdvisoriesYet: "No Advisories Yet",
    checkBackLater: "Check back later for farming recommendations and alerts",
    affectsCrop: "Affects",
    recently: "Recently",
    sourceLabel: "Source",
    readyToTransform: "Ready to Transform Your Farming?",
    joinThousands: "Join thousands of farmers who are already benefiting from AI-powered agricultural guidance",
    averageYieldIncrease: "Average Yield Increase",
    aiSupportAvailable: "AI Support Available",
    goodConditions: "Good conditions for irrigation",
    noWeatherData: "No weather data",
    noCropRecommendations: "No crop recommendations",
    noResourceData: "No resource data",
    noRecentAdvisories: "No recent advisories",
    noResultsFound: "No Results Found",
    tryDifferentKeywords: "Try searching with different keywords",
    aiPoweredAssistant: "24/7 AI-Powered Farming Assistant",
    personalizedAdvice: "Get personalized crop guidance, weather alerts, and expert farming advice powered by AI",
    getPersonalizedAdvice: "Comprehensive Agricultural Support",
    selectSoilType: "Select Soil Type",
    selectSoilTypePlaceholder: "Select soil type",
    nutrientLevels: "Nutrient Levels",
    soilHealthAssessment: "Soil Health Assessment",
    newAnalysis: "New Analysis",
    identifyManage: "Identify and manage crop pests and diseases effectively",
    urgentAlerts: "urgent alerts require attention",
    suitableForRegion: "Suitable for your region and climate",
    demoFarmer: "Demo Farmer",
  },
  hi: {
    appName: "किसान सहायक",
    tagline: "AI-संचालित कृषि मार्गदर्शन के साथ किसानों को सशक्त बनाना",
    getStarted: "शुरू करें",
    learnMore: "और जानें",
    dashboard: "डैशबोर्ड",
    weather: "मौसम",
    crops: "फसलें",
    chatbot: "AI सहायक",
    soilAnalysis: "मिट्टी विश्लेषण",
    resources: "संसाधन",
    pestDisease: "कीट और रोग",
    advisories: "सलाह",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    welcome: "स्वागत है",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    save: "सहेजें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    close: "बंद करें",
    next: "अगला",
    previous: "पिछला",
    search: "खोजें",
    filter: "फ़िल्टर",
    sort: "क्रमबद्ध करें",
    viewAll: "सभी देखें",
    heroTitle: "स्मार्ट खेती यहाँ शुरू होती है",
    heroSubtitle: "AI द्वारा संचालित व्यक्तिगत फसल मार्गदर्शन, मौसम अलर्ट और विशेषज्ञ कृषि सलाह प्राप्त करें",
    featuresTitle: "व्यापक कृषि सहायता",
    weatherTitle: "रियल-टाइम मौसम और पूर्वानुमान",
    weatherDesc: "खेती की सिफारिशों के साथ 5-दिन का पूर्वानुमान",
    cropGuidanceTitle: "फसल चयन मार्गदर्शन",
    cropGuidanceDesc: "अपनी मिट्टी और मौसम के लिए सही फसलें चुनें",
    aiChatTitle: "AI-संचालित सहायक",
    aiChatDesc: "आपके सभी कृषि प्रश्नों के लिए 24/7 सहायता",
    resourceTitle: "संसाधन अनुकूलन",
    resourceDesc: "पानी, उर्वरक, कीटनाशक उपयोग ट्रैक और अनुकूलित करें",
    soilTitle: "मिट्टी विश्लेषण",
    soilDesc: "उर्वरक और पोषक तत्व की सिफारिशें प्राप्त करें",
    pestTitle: "कीट और रोग प्रबंधन",
    pestDesc: "प्रारंभिक चेतावनी और उपचार समाधान",
    todayWeather: "आज का मौसम",
    temperature: "तापमान",
    humidity: "आर्द्रता",
    rainfall: "वर्षा",
    wind: "हवा की गति",
    recommendedCrops: "अनुशंसित फसलें",
    season: "मौसम",
    soilType: "मिट्टी का प्रकार",
    waterReq: "पानी की आवश्यकता",
    expectedYield: "अपेक्षित उपज",
    profit: "लाभ अनुमान",
    duration: "अवधि",
    days: "दिन",
    resourceUsage: "संसाधन उपयोग",
    water: "पानी",
    fertilizer: "उर्वरक",
    pesticide: "कीटनाशक",
    optimal: "इष्टतम",
    current: "वर्तमान",
    efficiency: "दक्षता",
    recentAdvisories: "हाल की सलाह",
    critical: "महत्वपूर्ण",
    warning: "चेतावनी",
    info: "जानकारी",
    askQuestion: "खेती के बारे में कुछ भी पूछें...",
    voiceInput: "आवाज इनपुट",
    sendMessage: "भेजें",
    analyzing: "विश्लेषण कर रहे हैं...",
    soilAnalysisTitle: "मिट्टी पोषक तत्व विश्लेषण",
    nitrogenLevel: "नाइट्रोजन (N)",
    phosphorusLevel: "फास्फोरस (P)",
    potassiumLevel: "पोटैशियम (K)",
    phLevel: "pH स्तर",
    organicMatter: "जैविक पदार्थ",
    getRecommendations: "सिफारिशें प्राप्त करें",
    recommendations: "सिफारिशें",
    pestDiseaseTitle: "कीट और रोग पहचान",
    symptoms: "लक्षण",
    treatment: "उपचार",
    prevention: "रोकथाम",
    severity: "गंभीरता",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    farmLocation: "खेत स्थान",
    farmSize: "खेत का आकार",
    phoneNumber: "फोन नंबर",
    language: "भाषा",
    english: "English",
    hindi: "हिंदी",
    servingFarmers: "भारत भर में 50,000+ किसानों की सेवा",
    trusted: "देशभर के किसानों द्वारा भरोसेमंद",
    exploreCrops: "अपने क्षेत्र और मौसम के लिए फसल सिफारिशें देखें",
    latestAdvisories: "नवीनतम कृषि सिफारिशें और अलर्ट",
    noCropsAvailable: "कोई फसल उपलब्ध नहीं",
    cropsWillAppear: "फसल की सिफारिशें यहां दिखाई देंगी",
    noAdvisoriesYet: "अभी तक कोई सलाह नहीं",
    checkBackLater: "कृषि सिफारिशों और अलर्ट के लिए बाद में देखें",
    affectsCrop: "प्रभावित करता है",
    recently: "हाल ही में",
    sourceLabel: "स्रोत",
    readyToTransform: "अपनी खेती को बदलने के लिए तैयार हैं?",
    joinThousands: "हजारों किसानों में शामिल हों जो पहले से ही AI-संचालित कृषि मार्गदर्शन से लाभान्वित हो रहे हैं",
    averageYieldIncrease: "औसत उपज वृद्धि",
    aiSupportAvailable: "AI सहायता उपलब्ध",
    goodConditions: "सिंचाई के लिए अच्छी स्थिति",
    noWeatherData: "कोई मौसम डेटा नहीं",
    noCropRecommendations: "कोई फसल सिफारिशें नहीं",
    noResourceData: "कोई संसाधन डेटा नहीं",
    noRecentAdvisories: "कोई हाल की सलाह नहीं",
    noResultsFound: "कोई परिणाम नहीं मिला",
    tryDifferentKeywords: "विभिन्न कीवर्ड के साथ खोजने का प्रयास करें",
    aiPoweredAssistant: "24/7 AI-संचालित कृषि सहायक",
    personalizedAdvice: "AI द्वारा संचालित व्यक्तिगत फसल मार्गदर्शन, मौसम अलर्ट और विशेषज्ञ कृषि सलाह प्राप्त करें",
    getPersonalizedAdvice: "व्यापक कृषि सहायता",
    selectSoilType: "मिट्टी का प्रकार चुनें",
    selectSoilTypePlaceholder: "मिट्टी का प्रकार चुनें",
    nutrientLevels: "पोषक तत्व स्तर",
    soilHealthAssessment: "मिट्टी स्वास्थ्य मूल्यांकन",
    newAnalysis: "नया विश्लेषण",
    identifyManage: "फसल कीटों और रोगों की प्रभावी ढंग से पहचान और प्रबंधन करें",
    urgentAlerts: "तत्काल अलर्ट ध्यान देने की आवश्यकता है",
    suitableForRegion: "आपके क्षेत्र और जलवायु के लिए उपयुक्त",
    demoFarmer: "डेमो किसान",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
